config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">


</head>

<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= pages_one_path %>">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Page one", pages_one_path %></li>
      <li><%= link_to "Page two", pages_two_path %></li>
      <li><%= link_to "page three", pages_three_path %></li>
    </ul>
  </div>
</nav>

  <%= yield %>

</body>

</html>

app/views/pages/one.html.erb
<h1>Boris Miranda Nuñez Alex</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2> Lorem ipsum dolor sit amet consectetur adipiscing elit fusce nisl, rutrum duis pulvinar phasellus velit luctus montes nascetur, mauris eleifend sagittis iaculis fermentum ad ac nullam. Sapien maecenas arcu augue rutrum etiam tristique facilisi convallis ad viverra ut quis posuere, aliquet volutpat suscipit vel facilisis ridiculus ac sem id ullamcorper quisque sociosqu. Nunc a curabitur etiam torquent platea vulputate dignissim inceptos dapibus sollicitudin, aliquam imperdiet placerat facilisis quam ullamcorper hendrerit nec maecenas nullam conubia, commodo pharetra convallis cras blandit nam ultrices posuere taciti. <h2>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>
<%= image_tag "img1.png" %>